Alquileres/urls.py
from django.urls import path
from .views import crear_alquiler, listado_alquiler

urlpatterns = [
    path('crear_alquiler/', crear_alquiler, name="crear_alquiler"),
    path('listado_alquiler/', listado_alquiler, name="listado_alquiler"),
]

CAP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Servicios.urls')),
    path('Alquileres/',include('Alquileres.urls')),
    path('sesion/',include('sesion.urls'),)
]

Servicios/urls.py
from django.urls import path

from Servicios.views import inicio, crear_servicios, listado_servicios,listado_excel


urlpatterns = [
    path('', inicio, name="inicio"),
    path('crear_servicios/', crear_servicios, name="crear_servicios"),
    path('listado_servicios/', listado_servicios, name="listado_servicios"),
    path('listado_excel/',listado_excel, name="listado_excel")
]

sesion/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from sesion import views


app_name='sesion'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('misdatos/', views.misdatos,name='misdatos'),
]

Alquileres/models.py
from django.db import models

# Create your models here.
class Alquileres(models.Model):
    nombre=models.CharField(max_length=30)
    cuit=models.IntegerField()
    direccion=models.CharField(max_length=30)
    inicio_contrato=models.DateField()
    sector=models.IntegerField()
    lugar=models.IntegerField()
    
    def __str__(self):
        return self.nombre 

Servicios/models.py
from django.db import models

# Create your models here.

#Base de dato
class Prueba(models.Model):
    nombre= models.CharField(max_length=30)
    edad= models.IntegerField()
    fecha_creacion=models.DateField(null=True)
    
    def __str__(self):
        return self.nombre 

sesion/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Permission, Group

class Usuario(AbstractUser):
    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name='user permissions',
        blank=True,
        related_name='custom_user_set',  # Cambia 'custom_user_set' por el nombre que prefieras
        help_text='The permissions this user has',
        related_query_name='user',
    )
    groups = models.ManyToManyField(
        Group,
        verbose_name='groups',
        blank=True,
        related_name='custom_user_set',  # Cambia 'custom_user_set' por el nombre que prefieras
        help_text='The groups this user belongs to',
        related_query_name='user',
    )
    pass

# Create your models here.

Alquileres/forms.py
from django import forms

class Formulario_Alquiler(forms.Form):
    nombre=forms.CharField(max_length=30)
    cuit=forms.IntegerField()
    direccion=forms.CharField(max_length=30)
    inicio_contrato=forms.DateField()
    sector=forms.IntegerField()
    lugar=forms.IntegerField()

Servicios/forms.py
from django import forms

class Formulario(forms.Form):
    #aca se especifican los campos del formulario
    nombre = forms.CharField()
    edad= forms.IntegerField()
    fecha_creacion=forms.DateField()
    

Alquileres/views.py
from django.shortcuts import render
from .forms import Formulario_Alquiler
from .models import Alquileres

# Create your views here.

def crear_alquiler(request):
    formulario_alquiler=Formulario_Alquiler()
    lista= Alquileres.objects.all()
    
    
    if request.method== 'POST':
        formulario_alquiler=Formulario_Alquiler(request.POST)
        
        if formulario_alquiler.is_valid():
            data=formulario_alquiler.cleaned_data
            datos= Alquileres(
                nombre=data.get('nombre'),
                cuit=data.get('cuit'),
                direccion=data.get('direccion'),
                inicio_contrato=data.get('inicio_contrato'),
                sector=data.get('sector'),
                lugar=data.get('lugar'),)
            datos.save()
            datos=Alquileres.objects.all()
            return render(request, 'Alquileres/listado_alquiler.html',{'datos':datos})
        else:
            return render(request,'Alquileres/crear_alquiler.html',{'formulario_alquiler':formulario_alquiler})
    
    return render(request,'Alquileres/crear_alquiler.html',{'formulario_alquiler':formulario_alquiler,"lista":lista})

def listado_alquiler(request):
    lista= Alquileres.objects.all()
    return render(request,'Alquileres/listado_alquiler.html',{"lista":lista})

Servicios/views.py
from datetime import datetime
from django.shortcuts import render
from .forms import Formulario
from .models import Prueba
from openpyxl import load_workbook

# Create your views here.
def inicio (request):
   fecha= datetime.now()
   return render(request, 'index.html',{'fecha':fecha})

def crear_servicios(request):
   # nombre= request.POST.get('nombre')
   # edad= request.POST.get('edad')
   # datos = Prueba(nombre=nombre,edad=edad, fecha_creacion=datetime.now())
   # datos.save()
   miformulario1=Formulario()
   
   if request.method== 'POST':
      miformulario=Formulario(request.POST)
      
      if miformulario.is_valid():
         data= miformulario.cleaned_data
         datos= Prueba(nombre=data.get('nombre'),edad=data.get('edad'), fecha_creacion=datetime.now())
         datos.save()
         mensaje='Guardado con exito'
         datos= Prueba.objects.all()
         return render(request,'Servicios/listado_servicios.html', {'mensaje':mensaje,'datos':datos})
      else:
         return render(request,'Servicios/crear_servicios.html',{'miformulario':miformulario})
      
   return render(request,'Servicios/crear_servicios.html',{'miformulario':miformulario1})

def listado_servicios(request):
   datos= Prueba.objects.all()
   return render(request,'Servicios/listado_servicios.html',{'datos':datos})

def listado_excel(request):
   archivo_excel=r'C:\Users\CHAZA\Documents\Python\CAP\2023.xlsx'
   
   libro= load_workbook(archivo_excel)
   hoja=libro['Hoja1']
   datos = []
   
   for fila in hoja.iter_rows(values_only=True):
      datos.append(fila)
   
   titulo=datos.pop(0)
   return render(request,'Servicios/listado_excel.html',{'datos':datos,'titulo':titulo})

sesion/views.py
from typing import Any, Dict
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect

# Create your views here.

class CustomLoginView(LoginView):
    template_name = 'login.html'
    success_url='misdatos'

    def get_success_url(self):
        return redirect('misdatos.hml')  # Ruta a la página de destino después del inicio de sesión

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['title'] = 'Iniciar sesion'
        return context
    
@login_required
def misdatos(request):
    sesion=request
    
    return render(request,'registration/misdatos.html',{'sesion':sesion})

templates/Alquileres/crear_alquiler.html
{% extends 'index.html' %}{% load static%} {% block css %}
<link rel="stylesheet" href="{% static 'css/alquileres/crear_alquiler.css'%}">
<link rel="stylesheet" href="{% static 'css/base.css'%}"> {% endblock %} {% block title %}ALQUILER{% endblock %}{% block centro %}
<h2 class="h1_crear_alquileres">NUEVO ALQUILER</h2>

<form action="{% url 'crear_alquiler' %}" method="POST">
    {% csrf_token %}
    <table>{{formulario_alquiler.as_table}}</table>
    <button>ENVIAR</button>
</form>
<hr> {% for i in lista%}
<p>{{i}}</p>
{% endfor %}
<a href="{% url 'listado_alquiler' %}">Lsitado</a> {% endblock%}

templates/Alquileres/listado_alquiler.html
{% extends 'index.html' %}{% load static%} {% block css %}
<link rel="stylesheet" href="{% static 'css/alquileres/crear_alquiler.css'%}">
<link rel="stylesheet" href="{% static 'css/base.css'%}"> {% endblock %} {% block title %}ALQUILER{% endblock %}{% block centro %}
<h2 class="h1_crear_alquileres">LISTADO</h2>

{% for i in lista%}
<p>{{i}}</p>
{% endfor %}
<button><a href="{% url 'inicio'%}">INICIO</a></button>{% endblock %}

templates/Servicios/crear_servicios.html
{% extends 'index.html' %}{% load static%} {% block title %}Servicios{% endblock %}{% block centro %}


<form action="{% url 'crear_servicios' %}" method="POST">
    {% csrf_token %}
    <table>
        {{miformulario.as_table}}
    </table>

    <button>CREAR</button>
</form>


<a href="{% url 'listado_servicios' %}">Listado</a> {% endblock%}

templates/Servicios/listado_excel.html
{% extends 'index.html' %}{% load static%} 
{% block css %}
    <link rel="stylesheet" href="{% static 'css/Servicios/listado_excel.css'%}">
    <link rel="stylesheet" href="{% static 'css/base.css'%}"> {% endblock %}
{% block title %}Excel{% endblock %}{% block centro %}

<div class="container">    
 <table class="table table-bordered ">
    <thead class="listado_excel_h1">
        <tr>
            <th>{{titulo.2 | slice:"3:"}}</th>
            <th>{{titulo.11| slice:"3:"}}</th>
            <th>{{titulo.12| slice:"3:"}}</th>
            <th>{{titulo.14| slice:"3:"}}</th>
            <th>{{titulo.15| slice:"3:"}}</th>
            <th>{{titulo.16| slice:"3:"}}</th>
            <th>{{titulo.20| slice:"3:"}}</th>
            <th>{{titulo.21| slice:"3:"}}</th>
            <th>{{titulo.24| slice:"3:"}}</th>
            <th>{{titulo.27| slice:"3:"}}</th>
            <th>{{titulo.28| slice:"3:"}}</th>
            <th>{{titulo.36| slice:"3:"}}</th>
            <th class="ultima-columna">{{titulo.37| slice:"3:"}}</th>
        </tr>
    </thead>
    <tbody>
        {% for fila in datos %}
        <tr class="listado_excel_h1">
            <td>{{fila.2}}</td>
            <td>{{fila.11 | date:'d/m/y'}}</td>
            <td>{{fila.12 | date:'d/m/y'}}</td>
            <td>{{fila.14}}</td>
            <td>{{fila.15}}</td>
            <td>{{fila.16}}</td>
            <td>${{fila.20 |floatformat:2}}</td>
            <td>${{fila.21 |floatformat:2}}</td>
            <td>${{fila.24|floatformat:2}}</td>
            <td>{{fila.27}}</td>
            <td>{{fila.28}}</td>
            <td>{{fila.36}}</td>
            <td class="ultima-columna">{{fila.37}}</td>
        </tr>
        {% endfor %}
    </tbody>
 </table>
</div>
    {% endblock%}

templates/Servicios/listado_servicios.html
{% extends 'index.html' %}{% load static%} {% block title %}INICIAR SESION{% endblock %}{% block centro %}

    <!-- Esto viene de views.crear-->
    <h1>{{mensaje}}</h1>

    <p>Estos son los datos ingresados:</p>

    <ul>{% for datos in datos %}
        <li>
            {{datos}}: de {{datos.edad}} años
        </li>{% endfor %}
    </ul>


    <button><a href="{% url 'crear_servicios'%}">CREAR</a></button>

    {% endblock%}

templates/index.html
{% load static%}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'css/index.css'%}">
    <link rel="stylesheet" href="{% static 'css/base.css'%}"> {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>

<body>
    <div class="container caja_titulo">
        <h1 class="titulo">TAVERNITI</h1>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'inicio'%}">HOME</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="{% url 'crear_alquiler'%}">ALQUILER</a>
                        <a class="nav-link" href="{% url 'listado_excel'%}">LISTADO</a>
                        <a class="nav-link" href="{% url 'crear_servicios'%}">SERVICIOS</a> {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'sesion:logout' %}">CERRAR SESION</a> {% else %}
                        <a class="nav-link" href="{% url 'sesion:login' %}">INICIAR SESION</a> {% endif %}
                        {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'sesion:misdatos' %}">Mis datos</a> {% endif %}

                    </div>
                </div>
            </div>
        </nav>
    </div>
    <p></p>
    <div class="continer centro ">
        {% block centro %} {% endblock %}
    </div>
</body>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js " integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE " crossorigin="anonymous "></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js " integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ " crossorigin="anonymous "></script>

</html>

templates/listado.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <!-- Esto viene de views.crear-->
    <h1>{{mensaje}}</h1>

    <p>Estaba en la base de datos</p>

    <ul>{% for datos in datos %}
        <li>
            {{datos}}
        </li>{% endfor %}
    </ul>

    <button><a href="{% url 'inicio'%}">Inicio</a></button>
    <button><a href="{% url 'listado'%}">Listado</a></button>

</body>

</html>